/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xgkawoceupybqcauapiz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhna2F3b2NldXB5YnFjYXVhcGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1NDExNjIsImV4cCI6MjA4MzExNzE2Mn0.duY9ziXViHxBrNtQS-AI2UOL1Ev-jeXEsJcgZ6fSf3c"